### PR TITLE
Support suffix

### PR DESCRIPTION
**Pull request by Tarrowren**
https://github.com/Tarrowren/css-class-intellisense/issues/15

### CODE REVIEW

**Comment by marijnh** [comment]
What feature does this implement (the linked issue explains absolutely nothing)?

**Comment by Tarrowren** [comment]
I added the suffix feature.

https://sass-lang.com/documentation/style-rules/parent-selector/

image

**Comment by marijnh** [comment]
Why did you include `selector?` in the rule? It seems to work just as well without that.

**Comment by Tarrowren** [comment]
suffix is used for className, which I think is close to classSelector.

suffix is not currently parsed correctly.
image

**Comment by marijnh** [comment]
That doesn't answer my question about the use of `selector?` in the new rule at all. Attached patch implements this in a way that seems more correct to me.

**Comment by Tarrowren** [comment]
Sorry, I misunderstood what you said. It's not appropriate to use `selector?` here.

**Pull request closed without merging**
